#!/usr/bin/env python3
"""
SMTP Setup Script for HealthyRizz
This script helps you configure SMTP email settings
"""

import os
import sys

def create_env_file():
    """Create .env file with SMTP configuration"""
    
    print("🔧 SMTP Email Setup for HealthyRizz")
    print("=" * 50)
    print()
    
    # Check if .env file already exists
    if os.path.exists('.env'):
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ").lower()
        if response != 'y':
            print("Setup cancelled.")
            return False
    
    print("📧 Let's configure your SMTP email settings")
    print()
    
    # Get SMTP settings from user
    print("For Gmail SMTP (Recommended for testing):")
    print("- Server: smtp.gmail.com")
    print("- Port: 587")
    print("- TLS: Yes")
    print()
    
    smtp_server = input("SMTP Server (default: smtp.gmail.com): ").strip() or "smtp.gmail.com"
    smtp_port = input("SMTP Port (default: 587): ").strip() or "587"
    use_tls = input("Use TLS? (y/N, default: y): ").lower() != 'n'
    
    print()
    print("📧 Email Account Settings:")
    email_username = input("Email Username (e.g., yourname@gmail.com): ").strip()
    
    if not email_username:
        print("❌ Email username is required!")
        return False
    
    print()
    print("🔐 Password Setup:")
    print("For Gmail:")
    print("1. Enable 2-Factor Authentication on your Google account")
    print("2. Go to Google Account Settings > Security > App passwords")
    print("3. Generate an App Password for 'Mail'")
    print("4. Use the 16-character App Password (not your regular password)")
    print()
    
    email_password = input("Email Password/App Password: ").strip()
    
    if not email_password:
        print("❌ Email password is required!")
        return False
    
    # Create .env content
    env_content = f"""# HealthyRizz Environment Configuration
# Generated by setup_smtp.py

# Flask Secret Key
SECRET_KEY=healthyrizz-super-secret-key-2024-change-in-production

# CSRF Protection Key
WTF_CSRF_SECRET_KEY=healthyrizz-csrf-secret-key-2024-change-in-production

# Application Settings
FLASK_ENV=development
DEBUG=False

# Database Configuration
DATABASE_URL=sqlite:///healthyrizz.db

# Email Configuration (SMTP)
MAIL_SERVER={smtp_server}
MAIL_PORT={smtp_port}
MAIL_USE_TLS={str(use_tls)}
MAIL_USERNAME={email_username}
MAIL_PASSWORD={email_password}
MAIL_DEFAULT_SENDER={email_username}

# Admin Email (for notifications)
ADMIN_EMAIL={email_username}

# Payment System (Razorpay) - Test keys
RAZORPAY_KEY_ID=rzp_test_default_key_id
RAZORPAY_KEY_SECRET=default_key_secret_for_testing
RAZORPAY_WEBHOOK_SECRET=default_webhook_secret_for_testing

# Session Settings
SESSION_COOKIE_SECURE=False
WTF_CSRF_SSL_STRICT=False
PERMANENT_SESSION_LIFETIME=1800

# File Upload Settings
MAX_CONTENT_LENGTH=16777216
UPLOAD_FOLDER=static/uploads
"""
    
    # Write .env file
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print("✅ .env file created successfully!")
        print()
        print("📋 Configuration Summary:")
        print(f"   SMTP Server: {smtp_server}")
        print(f"   SMTP Port: {smtp_port}")
        print(f"   Use TLS: {use_tls}")
        print(f"   Username: {email_username}")
        print(f"   Password: {'*' * len(email_password)}")
        print()
        
        print("🚀 Next Steps:")
        print("1. Run: python test_smtp_email.py")
        print("2. Check your email inbox for the test message")
        print("3. If successful, you can now send emails from your app!")
        
        return True
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return False

def test_smtp_configuration():
    """Test the SMTP configuration"""
    print()
    print("🧪 Testing SMTP Configuration...")
    print("=" * 40)
    
    try:
        # Import and run the test
        from test_smtp_email import test_smtp_email
        return test_smtp_email()
    except Exception as e:
        print(f"❌ Error testing SMTP: {e}")
        return False

if __name__ == "__main__":
    print("Welcome to HealthyRizz SMTP Setup!")
    print()
    
    # Create .env file
    if create_env_file():
        # Ask if user wants to test immediately
        print()
        test_now = input("Do you want to test the SMTP configuration now? (Y/n): ").lower()
        if test_now != 'n':
            test_smtp_configuration()
    
    print()
    print("Setup complete! 🎉") 