"""Initial migration

Revision ID: 6af3761b666d
Revises: 
Create Date: 2025-06-12 09:59:03.158302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af3761b666d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('daily_meal_prep')
    # op.drop_table('subscriptions')
    # op.drop_table('subscription_veg_days')
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_time', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.create_foreign_key('fk_delivery_subscription', 'subscription', ['subscription_id'], ['id'])
        batch_op.drop_column('status_updated_at')
        batch_op.drop_column('tracking_number')
        batch_op.drop_column('notes')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('tag',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('calories',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('protein',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('carbs',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('fat',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('price_trial')
        batch_op.drop_column('price_monthly_with_breakfast')
        batch_op.drop_column('is_low_carb')
        batch_op.drop_column('image_url')
        batch_op.drop_column('price_trial_without_breakfast')
        batch_op.drop_column('price_weekly_without_breakfast')
        batch_op.drop_column('is_high_protein')
        batch_op.drop_column('is_vegan')
        batch_op.drop_column('price_monthly_without_breakfast')
        batch_op.drop_column('is_dairy_free')
        batch_op.drop_column('is_paleo')
        batch_op.drop_column('is_popular')
        batch_op.drop_column('price_trial_with_breakfast')
        batch_op.drop_column('price_weekly_with_breakfast')
        batch_op.drop_column('is_gluten_free')
        batch_op.drop_column('is_keto')

    with op.batch_alter_table('skipped_delivery', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'subscription', ['subscription_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skipped_delivery', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'subscriptions', ['subscription_id'], ['id'])

    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_keto', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_gluten_free', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('price_weekly_with_breakfast', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('price_trial_with_breakfast', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('is_popular', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_paleo', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_dairy_free', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('price_monthly_without_breakfast', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('is_vegan', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_high_protein', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('price_weekly_without_breakfast', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('price_trial_without_breakfast', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_low_carb', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('price_monthly_with_breakfast', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('price_trial', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.alter_column('fat',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('carbs',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('protein',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('calories',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('tag',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('tracking_number', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('status_updated_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('fk_delivery_subscription', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subscriptions', ['subscription_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('address')
        batch_op.drop_column('delivery_time')

    op.create_table('subscription_veg_days',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('meal_plan_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=7), nullable=False),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('current_period_start', sa.DATETIME(), nullable=True),
    sa.Column('current_period_end', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), nullable=True),
    sa.Column('pause_collection', sa.BOOLEAN(), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('delivery_days', sa.VARCHAR(length=20), nullable=True),
    sa.Column('vegetarian_days', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('delivery_address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('delivery_city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('delivery_province', sa.VARCHAR(length=100), nullable=True),
    sa.Column('delivery_postal_code', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_table('daily_meal_prep',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('prep_date', sa.DATE(), nullable=False),
    sa.Column('meal_plan_id', sa.INTEGER(), nullable=False),
    sa.Column('veg_meals_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('nonveg_meals_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('with_breakfast_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('without_breakfast_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
